config/routes.rb
Rails.application.routes.draw do
  match 'check/:id' => 'homepage#check' , via: [:post], :as => :check
  match '/paytm_payment' => 'paytm#start_payment', via: [:post], :as => :paytm_payment
  match '/confirm_payment' => 'paytm#verify_payment', via: [:post]
  devise_for :users
  get '/landingpage/map/:id', to: 'landingpage#map', :as => :map
  resources:admin
 resources :homepage
 resources :landingpage
 resources :cart
 resources :orders
 authenticated :user do
  root 'landingpage#index', as: "authenticated_root"
 end
  root 'homepage#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord
    belongs_to :user
end

app/models/item.rb
class Item < ApplicationRecord
    belongs_to :user
end

app/models/order.rb
class Order < ApplicationRecord
    belongs_to :user
end

app/models/otp.rb
class Otp < ApplicationRecord
end

app/models/search.rb
class Search < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :carts
  has_many :items
  has_many :orders
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  def index
    @items = Item.where(user_id:current_user)
  end

  def new
  end

  def create
    @item = current_user.items.build(item_params)
    if @item.save
      redirect_to admin_index_path
    else
      render "new"
    end
  end

  def destroy
    @f = Item.find(params[:id])
    @f.destroy
    redirect_to admin_index_path
  end

   private
   def item_params
    params.require(:item).permit(:hotel, :name, :describe, :foodtype, :price, :img)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?
  protected
       def configure_permitted_parameters
            devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:mobile, :name, :email, :password)}

            devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:mobile, :name, :email, :password, :current_password)}
       end

end

app/controllers/cart_controller.rb
class CartController < ApplicationController
  def index
    @cartitem = Cart.where(user_id:current_user)
  end
 def destroy
  @f = Cart.find(params[:id])
  @f.destroy
  redirect_to cart_index_path
 end
end

app/controllers/homepage_controller.rb
class HomepageController < ApplicationController
  require 'openssl'
  OpenSSL::SSL::VERIFY_PEER = OpenSSL::SSL::VERIFY_NONE 

  def index
  end

  def new
  end

  def create
    @sample = mobile_params
    @generate = rand(10 ** 4)
    sendotp = @generate
    @genotp  =Otp.new(otpcode:@generate)
    require 'rubygems' 
    require 'twilio-ruby' 
    account_sid = 'ACaee7fdb632a978373799bd29384bc82f' 
    auth_token = '8c27aa0c2ebe5fcbfe4f6f360b4067bf' 
    @client = Twilio::REST::Client.new(account_sid, auth_token) 
    message = @client.messages.create( 
                                 body: sendotp, 
                                 from: '+12055397687',
                                 to: '+919677861286')
    if @genotp.save
      redirect_to homepage_path(@genotp)
    else
      render "new"
    end
  end

  def show
@otpcode = Otp.find(params[:id])
@id = params[:id]
  end

  def check
    @original = Otp.find(params[:id])
    @sample = get_some
    @original1 = @original.otpcode
    fromform = @sample["otpcode"].to_i
    fromdb = @original1
    if fromform == fromdb
     redirect_to new_user_session_path
    else
      redirect_to homepage_path(@original)
    end
  end

  private
  def get_some
    params.require(:otp).permit(:otpcode)
  end
  def mobile_params
   params.require(:otp).permit(:mobile)
 end
end

app/controllers/landingpage_controller.rb
class LandingpageController < ApplicationController
  def index
    @items = Item.all.order("created_at DESC")
  end

 def create
   @value = mobile_params
   @data= Search.new(name:@value["search"])
   if @data.save
   redirect_to map_path(@data)
   end
 end

  def show
    @data = Item.find(params[:id])
    @item = current_user.carts.build(name:@data.name,hotel:@data.hotel,foodtype:@data.foodtype,img:@data.img,describe:@data.describe,price:@data.price)
    if @item.save
      redirect_to cart_index_path
    else
      render "root"
    end
  end

  def map
    @value = Search.find(params[:id])
    @search = @value["name"].capitalize()
    @data = Item.where(name:@search)
    if @data.length() ==0
      @search1 = @search.capitalize()
      @data= Item.where(hotel:@search1)
    end

  end

  private
  def mobile_params
      params.require(:order).permit(:search)
    end

end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController

    def index
        @order_item = Order.where(user_id:current_user)
    end

    def new
    end

    def show
      @ordered_item = Order.find(params[:id])
      require 'geocoder'
      Geocoder.configure(lookup: :opencagedata, api_key: "887ad43e20e04081a44d6775ed0b7d63")
      @results = Geocoder.search(@ordered_item["address"])
      @result = @results.first
      puts "#{@result.latitude}, #{@result.longitude}" 
    end

    def create
        @s = mobile_params
        @address1 = @s["address"]
        @id1 = @s["f"].to_i
        @data = Cart.find(@id1)
        @item = current_user.orders.build(name:@data.name,hotel:@data.hotel,foodtype:@data.foodtype,img:@data.img,describe:@data.describe,price:@data.price,address:@address1)
        if @item.save
            @data.destroy
        redirect_to order_path(@item)
        end
    end

    def destroy
        @f = Order.find(params[:id])
        @f.destroy
        redirect_to orders_path
       end

    private
    def mobile_params
        params.require(:order).permit(:address,:f)
      end

end

app/controllers/paytm_controller.rb
class PaytmController < ApplicationController
    include PaytmHelper
    skip_before_action :verify_authenticity_token
    def start_payment
      @s = mobile_params
      @address1 = @s["address"]
      @id1 = @s["f"].to_i
      @data = Cart.find(@id1)
      @item = current_user.orders.build(name:@data.name,hotel:@data.hotel,foodtype:@data.foodtype,img:@data.img,describe:@data.describe,price:@data.price,address:@address1)
        if @item.save
            @data.destroy
        end
      start_payment = Paytm::StartPaymentService.new(params, request)
      start_payment.call
      @checksum = start_payment.checksum
      @paytmParam = start_payment.paytmParam
    end
  
    def verify_payment
      paytm_verify = Paytm::VerifyPaymentService.new(params, @cart)
      paytm_verify.call
      @paytmparams = paytm_verify.paytmparams
      @is_valid_checksum = paytm_verify.is_valid_checksum
      @some = Order.last()
      if @is_valid_checksum == true
        if @paytmparams["STATUS"] == "TXN_SUCCESS"
          redirect_to order_path(@some)
        else
          respond_to do |format|
            format.html
          end
        end
      end
    end

    private

    def mobile_params
      params.require(:order).permit(:address,:f)
    end

end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cart_helper.rb
module CartHelper
end

app/helpers/homepage_helper.rb
module HomepageHelper
end

app/helpers/landingpage_helper.rb
module LandingpageHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/otp_helper.rb
module OtpHelper
end

app/helpers/paytm_helper.rb
module PaytmHelper
    require 'paytm/encryption_new_pg.rb'
    include EncryptionNewPG
    def generate_checksum
      new_pg_checksum(@paytmParam,"%SoAmYtc!%E4s6DN").gsub("\n",'')
    end
  
    def verify_checksum
      new_pg_verify_checksum(@paytmparams, @checksum_hash, "%SoAmYtc!%E4s6DN")
    end
end

app/views/homepage/index.html.erb
<div class="row mb-0">
<div class="col-lg-7 col-md-12">
<div class="container">
<div class="d-flex justify-content-between container pt-5">
<div>
<a href="https://www.swiggy.com/"><img src="https://i.pinimg.com/originals/69/df/f3/69dff3d81877bb46865f656de053e96e.png" width="230"/></a>
</div>
<div>
<p>
  <% if user_signed_in? %>
  <%= link_to "logout",destroy_user_session_path,method: :delete %>
  <%= link_to "Edit_profile" ,edit_user_registration_path %>
  <% else %>
<a class="login pr-4" href="http://localhost:3000/homepage/new">LOGIN</a>
<%= link_to "Sign up", new_user_registration_path, class: "btn text-white font-weight-bold px-4 py-2", style: "background-color:black;font-size:17px;border-radius:0;"%>
<% end %>
</p>
</div>
</div>
<p class="container mt-5">
<span class="text-black" style="font-weight:500;font-size:45px;">Late Night Office?</span>
<br>
<span class="font-weight-normal text-secondary" style="font-size:25px">Order food from favourite restaurants near you.</span>
</p>
<div class="d-flex pt-4">
<input required class="form-control home col-9 ml-3" style="border-radius:0;" placeholder="Enter Your order location" type="text"/>
<%= link_to "FIND FOOD", landingpage_index_path,class: "btn btn-lg font-weight-bold px-4 text-white py-4 ",style: "background-color:#ff5d0b;border-radius:0;font-size:16px;" %>
</div>
<p class="container mt-5 font-weight-normal text-secondary">POPULAR CITIES IN INDIA</span>
<div class="container">
<span class="font-weight-bold" style="font-size:16px;">Ahmedabad</span>
<span class="font-weight-bold mx-2  text-secondary" style="font-size:16px;">Bangalore</span>
<span class="font-weight-bold mx-2 " style="font-size:16px;">Chennai</span>
<span class="font-weight-bold mx-2 text-secondary" style="font-size:16px;">Delhi</span>
<span class="font-weight-bold mx-2 " style="font-size:16px;">Gurgaon</span>
<span class="font-weight-bold mx-2 text-secondary" style="font-size:16px;">Hyderabad</span>
<span class="font-weight-bold mx-2 " style="font-size:16px;">Kolkata</span>
<span class="font-weight-bold mx-2 text-secondary" style="font-size:16px;">Mumbai</span>
<span class="font-weight-bold mx-2 " style="font-size:16px;">Pune</span>
<span class="font-weight-bold mx-2 text-secondary" style="font-size:16px;">& more.</span>
</div>
</div>
</div>
<div class="col-5" style="padding-left:0px;"> 
<img class="img-fluid d-none d-lg-block" src="https://yennadosa.com/wp-content/uploads/2018/12/radhikashomepagefinal.jpg" style="height:600px !important;"/>
</div>
</div>
<div class="d-flex justify-content-around onsmall"  style="width:auto;height:400px;background-color:#2b1e16;">
<div>
<img src="https://res.cloudinary.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_210,h_398/4x_-_No_min_order_x0bxuf" width="120"/>
<br>
<p  class="text-white mt-2" style="font-size: 20px;
font-weight: 600;
margin-top: 0;">NO Minimum Order</p>
<p class="mt-5 d-none d-lg-block" style="font-size: 15px;
width: 260px;
color: #e0cbc1;
line-height: 1.3;">Order in for yourself or for the group, with no restrictions on order value</p>

</div>
<div>
<img src="https://res.cloudinary.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_224,h_412/4x_Live_order_zzotwy" width="120"/>
<p class="text-white mt-3" style="ffont-size: 20px;
font-weight: 600;
margin-top: 0;">Live Order Tracking</p>
<p class="mt-5 d-none d-lg-block" style="font-size: 15px;
width: 260px;
color: #e0cbc1;
line-height: 1.3;">Order in for yourself or for the group, with no restrictions on order value</p>

</div>
<div class="mt-4">
<img class="mb-2" src="https://res.cloudinary.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_248,h_376/4x_-_Super_fast_delivery_awv7sn" width="120"/>
<p class="text-white mt-3" style="font-size: 20px;
font-weight: 600;
margin-top: 0;">Fast-Delivery</p>
<p class="mt-5 d-none d-lg-block" style="font-size: 15px;
width: 260px;
color: #e0cbc1;
line-height: 1.3;">Order in for yourself or for the group, with no restrictions on order value</p>
</div>
</div>
<div class="row" style="height:550px;">
<div class="col-lg-5 col-sm-12">
<div class="container">
<div class="container">
<p class="font-weight-bold" style="font-size:34px;margin-top:150px;width:240px;line-height:1;">Restaurants in your pocket</p>
<p class="mt-2 font-weight-normal text-secondary">Order from your favorite restaurants & track on the go, with the all-new Swiggy app.</p>
<div class="d-flex pt-5">
<a href="https://play.google.com/store/apps/details?id=in.swiggy.android"><img style="cursor:pointer;" class="mr-3" src="https://res.cloudinary.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,h_108/play_ip0jfp" height="54" width="200"/></a>
<a href="https://apps.apple.com/in/app/swiggy-food-order-delivery/id989540920"><img style="cursor:pointer;"  src="https://res.cloudinary.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,h_108/iOS_ajgrty" height="54" width="200"/></a>
</div>
</div>
</div>

</div>
<div class=" col-7 d-none d-lg-block">
<div class="d-flex mt-0">
<img src="https://res.cloudinary.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_768,h_978/pixel_wbdy4n" height="489" width="384"/>
<img style="margin-top:80px;" src="https://res.cloudinary.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_768,h_978/iPhone_wgconp_j0d1fn" height="489" width="384"/>
</div
</div>
</div>
</div>

<div class="row py-4 mb-0"  style="margin-top:19px;border-bottom:2px solid black;background-color:black;">

<div class="col-lg-3 col-sm-12 pt-5">
<div class="container">
<p class="font-weight-bold text-secondary mb-2">COMPANY</p>
<a href="https://www.swiggy.com/"><p class="text-white font-weight-normal foot">About us</p></a>
<a href="https://www.swiggy.com/"><p class="text-white font-weight-normal foot">Team</p></a>
<a href="https://www.swiggy.com/"><p class="text-white font-weight-normal foot">Careers</p></a>
<a href="https://www.swiggy.com/"><p class="text-white font-weight-normal foot">Swiggy Blog</p></a>
<a href="https://www.swiggy.com/"><p class="text-white font-weight-normal foot">Bug Bounty</p></a>
<a href="https://www.swiggy.com/"><p class="text-white font-weight-normal foot">Swiggy Pop</p></a>
<a href="https://www.swiggy.com/"><p class="text-white font-weight-normal foot">Swiggy Super</p></a>
</div>
</div>

<div class="col-lg-3 col-sm-12 pt-5">
<div class="container">
<p class="font-weight-bold text-secondary">CONTACT</p>
<a href="https://www.swiggy.com/"><p class="text-white font-weight-normal foot">Help & Support</p></a>
<a href="https://www.swiggy.com/"><p class="text-white font-weight-normal foot">Partner with us</p></a>
<a href="https://www.swiggy.com/"><p class="text-white font-weight-normal foot">Ride with us</p></a>
</div>
</div>

<div class="col-lg-3 col-sm-12 pt-5">
<div class="container">
<p class="font-weight-bold text-secondary">LEGAL</p>
<a href="https://www.swiggy.com/"><p class="text-white font-weight-normal foot">Terms & Conditions</p></a>
<a href="https://www.swiggy.com/"><p class="text-white font-weight-normal foot">Refund & Cancellation</p></a>
<a href="https://www.swiggy.com/"><p class="text-white font-weight-normal foot">Privacy Policy</p></a>
<a href="https://www.swiggy.com/"><p class="text-white font-weight-normal foot">Cookie Policy</p></a>
<a href="https://www.swiggy.com/"><p class="text-white font-weight-normal foot">Offer Terms</p></a>
</div>
</div>

<div class="col-lg-3 col-sm-12 pt-5">
<div class="container">
<a  href="https://play.google.com/store/apps/details?id=in.swiggy.android"><img style="cursor:pointer;border-radius:10px;" class="border imgfoot" src="https://res.cloudinary.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,h_108/play_ip0jfp" height="54" width="200"/></a>
<a  href="https://apps.apple.com/in/app/swiggy-food-order-delivery/id989540920"><img class="border mt-lg-3 imgfoot mt-sm-0" style="cursor:pointer;border-radius:10px;"  src="https://res.cloudinary.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,h_108/iOS_ajgrty" height="54" width="200"/></a>
</div>
</div>
</div>

app/views/homepage/new.html.erb
<div style=" position:fixed;
top: 50%;
left: 50%;
width:30em;
height:18em;
margin-top: -13em;
margin-left: -16em;">
<a href="http://localhost:3000" class="d-flex justify-content-center" ><img src="https://i.pinimg.com/originals/69/df/f3/69dff3d81877bb46865f656de053e96e.png" width="230"/></a>
<h2 class="text-center mt-3">OTP  Generation</h2>

<%=form_for :otp, :url => {:action => "create"}, :method => "post" do |f| %>
    <div class="field d-flex justify-content-center">
    <%= f.text_field :mobile,placeholder: "Mobile No ",class: "form-control loginbox",:required => true %>
  </div>

  <div class="actions d-flex justify-content-center">
  <%= f.submit "Generate OTP",class: "my-4 btn btn-block text-white font-weight-bold",style: "background-color:#ff5d0b;border-radius:0;" %>
</div>
<% end %>
</div>

app/views/homepage/show.html.erb
<div style=" position:fixed;
top: 50%;
left: 50%;
width:30em;
height:18em;
margin-top: -13em;
margin-left: -16em;">
<a href="http://localhost:3000" class="d-flex justify-content-center" ><img src="https://i.pinimg.com/originals/69/df/f3/69dff3d81877bb46865f656de053e96e.png" width="230"/></a>
<h2 class="text-center mt-3">OTP Verification<br><p class="mt-2 pl-5" style="font-size:14px;">or <a href="http://localhost:3000/users/sign_up" style="color:#ff5d0b;">Resend OTP<a/><br><hr></p></h2>

<%=form_for :otp, :url => check_path{@id} do |f| %>
    <div class="field d-flex justify-content-center">
    <%= f.text_field :otpcode,placeholder: "Enter Your OTP",class: "form-control loginbox",:required => true %>
  </div>

  <div class="actions d-flex justify-content-center">
  <%= f.submit "NEXT",class: "my-4 btn btn-block text-white font-weight-bold",style: "background-color:#ff5d0b;border-radius:0;" %>
</div>
<% end %>
</div>

app/views/landingpage/index.html.erb
<div style="background-color:#171a29;height:340px;">
<div class="container pt-4">
<img class="mr-3 displayy imgg" width="260" height="260" src="https://res.cloudinary.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_520,h_520/rng/md/carousel/production/dya8c4z9hpf0hsifz7vx">
<img class="mr-3 d-none d-lg-inline imgg" width="260" height="260" src="https://res.cloudinary.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_520,h_520/rng/md/carousel/production/mudxtokgxfjemq0aii74">
<img class="mr-3 displayy imgg" width="260" height="260" src="https://res.cloudinary.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_520,h_520/rng/md/carousel/production/w9ikmnc6eigmlf5n1p91">
<img class="d-none d-lg-inline imgg" width="260" height="260" src="https://res.cloudinary.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_520,h_520/rng/md/carousel/production/ztpd5q9awnmmnefczn5x">
</div>
</div>

<div class="container mt-4">
<h4 class="mb-5 pb-4" style="font-size: 28px;font-weight: 600;border-bottom:2px solid gray;">Top Picks</h4>
</div>
<div class="container">
<div class="row">


<% @items.each  do |f| %>
    <div class=" col-lg-4 mb-5 d-flex justify-content-center">
    <div class="card" style="width: 18rem;border:0;">
    <%= image_tag f["img"],class: "card-img-top landingpageimage img-fluid" %>
    <div class="card-body">
    <p class="text-muted text-left m-0 p-0 font-weight-bold"><%= f["hotel"].upcase %></p>  
        <div class="card-title d-flex">
       <% if f["foodtype"]==="veg" %>
       <img style="margin-top:3px;" src="https://oslocks.files.wordpress.com/2014/11/vegetarian-symbol.png" width="20"  height="20"/>
       <% else %>
       <img style="margin-top:5px;" src="https://infoseekershub.com/wp-content/uploads/2019/08/non-veg.jpg" width="15"  height="15"/>
       <% end %>

        <h5 class="ml-2"><%= f["name"].capitalize %></h5>
        </div>
        <p class="card-subtitle mb-2 text-muted"><%= f["describe"].capitalize %></p>
        <div class="d-flex justify-content-between">
        <div><p class="text-muted" style="font-weight:600;">Rs.<%= f["price"] %></p></div>
        <% if user_signed_in? %>
        <div><%= link_to "ADD",landingpage_path(f),class: "btn text-success addbutton px-4 font-weight-bold",style: "border-radius:0;font-size:14px;" %></div>
        <% else %>
        <div><%= link_to "ADD",new_user_session_path,class: "btn text-success addbutton px-4 font-weight-bold",style: "border-radius:0;font-size:14px;" %></div>
        <% end %>
        </div>
      </div>
    </div>
    </div>
<% end %>
</div>
</div>

app/views/landingpage/map.html.erb
<% if @data.length() ==0 %>
<div class="back123">
</div>
<% else %>
<div class="container">
<h4 class="mb-5 mt-4 pb-4" style="font-size: 18px;font-weight: 600;border-bottom:2px solid gray;">Results for your search</h4>
</div>

<div class="container">
<div class="row">


<% @data.each  do |f| %>
    <div class=" col-lg-4 mb-5 d-flex justify-content-center">
    <div class="card" style="width: 18rem;border:0;">
    <%= image_tag f["img"],class: "card-img-top landingpageimage img-fluid" %>
    <div class="card-body">
    <p class="text-muted text-left m-0 p-0 font-weight-bold"><%= f["hotel"].upcase %></p>  
        <div class="card-title d-flex">
       <% if f["foodtype"]==="veg" %>
       <img style="margin-top:3px;" src="https://oslocks.files.wordpress.com/2014/11/vegetarian-symbol.png" width="20"  height="20"/>
       <% else %>
       <img style="margin-top:5px;" src="https://infoseekershub.com/wp-content/uploads/2019/08/non-veg.jpg" width="15"  height="15"/>
       <% end %>

        <h5 class="ml-2"><%= f["name"].capitalize %></h5>
        </div>
        <p class="card-subtitle mb-2 text-muted"><%= f["describe"].capitalize %></p>
        <div class="d-flex justify-content-between">
        <div><p class="text-muted" style="font-weight:600;">Rs.<%= f["price"] %></p></div>
        <% if user_signed_in? %>
        <div><%= link_to "ADD",landingpage_path(f),class: "btn text-success addbutton px-4 font-weight-bold",style: "border-radius:0;font-size:14px;" %></div>
        <% else %>
        <div><%= link_to "ADD",new_user_session_path,class: "btn text-success addbutton px-4 font-weight-bold",style: "border-radius:0;font-size:14px;" %></div>
        <% end %>
        </div>
      </div>
    </div>
    </div>
<% end %>
</div>
</div>
<% end %>