config/routes.rb
Rails.application.routes.draw do
  match 'check/:id' => 'homepage#check' , via: [:post], :as => :check
  match '/paytm_payment' => 'paytm#start_payment', via: [:post], :as => :paytm_payment
  match '/confirm_payment' => 'paytm#verify_payment', via: [:post]
  devise_for :users
  get '/landingpage/map/:id', to: 'landingpage#map', :as => :map
  resources:admin
 resources :homepage
 resources :landingpage
 resources :cart
 resources :orders
 authenticated :user do
  root 'landingpage#index', as: "authenticated_root"
 end
  root 'homepage#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord
    belongs_to :user
end

app/models/item.rb
class Item < ApplicationRecord
    belongs_to :user
end

app/models/order.rb
class Order < ApplicationRecord
    belongs_to :user
end

app/models/otp.rb
class Otp < ApplicationRecord
end

app/models/search.rb
class Search < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :carts
  has_many :items
  has_many :orders
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  def index
    @items = Item.where(user_id:current_user)
  end

  def new
  end

  def create
    @item = current_user.items.build(item_params)
    if @item.save
      redirect_to admin_index_path
    else
      render "new"
    end
  end

  def destroy
    @f = Item.find(params[:id])
    @f.destroy
    redirect_to admin_index_path
  end

   private
   def item_params
    params.require(:item).permit(:hotel, :name, :describe, :foodtype, :price, :img)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?
  protected
       def configure_permitted_parameters
            devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:mobile, :name, :email, :password)}

            devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:mobile, :name, :email, :password, :current_password)}
       end

end

app/controllers/cart_controller.rb
class CartController < ApplicationController
  def index
    @cartitem = Cart.where(user_id:current_user)
  end
 def destroy
  @f = Cart.find(params[:id])
  @f.destroy
  redirect_to cart_index_path
 end
end

app/controllers/homepage_controller.rb
class HomepageController < ApplicationController
  require 'openssl'
  OpenSSL::SSL::VERIFY_PEER = OpenSSL::SSL::VERIFY_NONE 

  def index
  end

  def new
  end

  def create
    @sample = mobile_params
    @generate = rand(10 ** 4)
    sendotp = @generate
    @genotp  =Otp.new(otpcode:@generate)
    require 'rubygems' 
    require 'twilio-ruby' 
    account_sid = 'ACaee7fdb632a978373799bd29384bc82f' 
    auth_token = '8c27aa0c2ebe5fcbfe4f6f360b4067bf' 
    @client = Twilio::REST::Client.new(account_sid, auth_token) 
    message = @client.messages.create( 
                                 body: sendotp, 
                                 from: '+12055397687',
                                 to: '+919677861286')
    if @genotp.save
      redirect_to homepage_path(@genotp)
    else
      render "new"
    end
  end

  def show
@otpcode = Otp.find(params[:id])
@id = params[:id]
  end

  def check
    @original = Otp.find(params[:id])
    @sample = get_some
    @original1 = @original.otpcode
    fromform = @sample["otpcode"].to_i
    fromdb = @original1
    if fromform == fromdb
     redirect_to new_user_session_path
    else
      redirect_to homepage_path(@original)
    end
  end

  private
  def get_some
    params.require(:otp).permit(:otpcode)
  end
  def mobile_params
   params.require(:otp).permit(:mobile)
 end
end

app/controllers/landingpage_controller.rb
class LandingpageController < ApplicationController
  def index
    @items = Item.all.order("created_at DESC")
  end

 def create
   @value = mobile_params
   @data= Search.new(name:@value["search"])
   if @data.save
   redirect_to map_path(@data)
   end
 end

  def show
    @data = Item.find(params[:id])
    @item = current_user.carts.build(name:@data.name,hotel:@data.hotel,foodtype:@data.foodtype,img:@data.img,describe:@data.describe,price:@data.price)
    if @item.save
      redirect_to cart_index_path
    else
      render "root"
    end
  end

  def map
    @value = Search.find(params[:id])
    @search = @value["name"].capitalize()
    @data = Item.where(name:@search)
    if @data.length() ==0
      @search1 = @search.capitalize()
      @data= Item.where(hotel:@search1)
    end

  end

  private
  def mobile_params
      params.require(:order).permit(:search)
    end

end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController

    def index
        @order_item = Order.where(user_id:current_user)
    end

    def new
    end

    def show
      @ordered_item = Order.find(params[:id])
      require 'geocoder'
      Geocoder.configure(lookup: :opencagedata, api_key: "887ad43e20e04081a44d6775ed0b7d63")
      @results = Geocoder.search(@ordered_item["address"])
      @result = @results.first
      puts "#{@result.latitude}, #{@result.longitude}" 
    end

    def create
        @s = mobile_params
        @address1 = @s["address"]
        @id1 = @s["f"].to_i
        @data = Cart.find(@id1)
        @item = current_user.orders.build(name:@data.name,hotel:@data.hotel,foodtype:@data.foodtype,img:@data.img,describe:@data.describe,price:@data.price,address:@address1)
        if @item.save
            @data.destroy
        redirect_to order_path(@item)
        end
    end

    def destroy
        @f = Order.find(params[:id])
        @f.destroy
        redirect_to orders_path
       end

    private
    def mobile_params
        params.require(:order).permit(:address,:f)
      end

end

app/controllers/paytm_controller.rb
class PaytmController < ApplicationController
    include PaytmHelper
    skip_before_action :verify_authenticity_token
    def start_payment
      @s = mobile_params
      @address1 = @s["address"]
      @id1 = @s["f"].to_i
      @data = Cart.find(@id1)
      @item = current_user.orders.build(name:@data.name,hotel:@data.hotel,foodtype:@data.foodtype,img:@data.img,describe:@data.describe,price:@data.price,address:@address1)
        if @item.save
            @data.destroy
        end
      start_payment = Paytm::StartPaymentService.new(params, request)
      start_payment.call
      @checksum = start_payment.checksum
      @paytmParam = start_payment.paytmParam
    end
  
    def verify_payment
      paytm_verify = Paytm::VerifyPaymentService.new(params, @cart)
      paytm_verify.call
      @paytmparams = paytm_verify.paytmparams
      @is_valid_checksum = paytm_verify.is_valid_checksum
      @some = Order.last()
      if @is_valid_checksum == true
        if @paytmparams["STATUS"] == "TXN_SUCCESS"
          redirect_to order_path(@some)
        else
          respond_to do |format|
            format.html
          end
        end
      end
    end

    private

    def mobile_params
      params.require(:order).permit(:address,:f)
    end

end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cart_helper.rb
module CartHelper
end

app/helpers/homepage_helper.rb
module HomepageHelper
end

app/helpers/landingpage_helper.rb
module LandingpageHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/otp_helper.rb
module OtpHelper
end

app/helpers/paytm_helper.rb
module PaytmHelper
    require 'paytm/encryption_new_pg.rb'
    include EncryptionNewPG
    def generate_checksum
      new_pg_checksum(@paytmParam,"%SoAmYtc!%E4s6DN").gsub("\n",'')
    end
  
    def verify_checksum
      new_pg_verify_checksum(@paytmparams, @checksum_hash, "%SoAmYtc!%E4s6DN")
    end
end

app/helpers/phone_verifications_helper.rb
module PhoneVerificationsHelper
end

app/views/cart/index.html.erb
<script>
$(document).ready(function(){
  $(".cash").hide()
  $(".online").hide()
  $(".enablecash").click(function(){
    $(".cash").show()
    $(".online").hide()
  })
  $(".enableonline").click(function(){
    $(".cash").hide()
    $(".online").show()
  })
}
)
</script>

<div class="container">
<% @cost = 0 %>
<% @count = 0 %>
<% if @cartitem.size<1 %>
<div class="back mt-5">
<div class="cartempty">
<p class="font-weight-bold text-secondary text-center font-italic" style="font-size:20px;">Your cart is empty</p>
<p class="text-center text-muted font-italic">You can go to home page to view more restaurants</p>
    <%= link_to "Add items",landingpage_index_path,class: "d-flex justify-content-center font-weight-bold btn px-4 text-white sa" %>
   </div>
    </div>
<% else %>
<p class="text-left my-5 pb-4 font-italic" style="font-size:22px;font-weight:600;border-bottom:2px solid gray;">YOUR CART</p>
<div class="row">
<div class="col-lg-12">
<% @cartitem.each do|f| %>
    <div class="row cart py-3 pr-3 mx-2 mb-4" style="background:alicewhite;">
    <div class="col-4">
    <% @price=1 %>
    <%= image_tag f["img"],class: "card-img" %>
    </div>
    <div class="col-8">
    <p class="text-muted text-left m-0 p-0 font-weight-bold"><%= f.hotel.upcase %></p>
    <div class="d-flex justify-content-between mt-3">  
       <div class="d-flex">
       <% if f["foodtype"]==="veg" %>
       <img style="margin-top:3px;" src="https://oslocks.files.wordpress.com/2014/11/vegetarian-symbol.png" width="20"  height="20"/>
       <% else %>
       <img style="margin-top:5px;" src="https://infoseekershub.com/wp-content/uploads/2019/08/non-veg.jpg" width="15"  height="15"/>
       <% end %>
        <h5 class="ml-2"><%= f["name"].capitalize %></h5>
        </div>
        <div class="d-flex">
        <i class="fa fa-plus p-2 plus" aria-hidden="true"></i>
        <p class="font-weight-bold price p-2 mb-0" style="margin-top:-5px;"><%= @price %></p>
        <i class="fa fa-minus p-2 minus" aria-hidden="true"></i>
        </div>
        </div>
        <% @cost += f["price"].to_f %>
        <% @count+=1 %>
        <p class="font-weight-normal text-muted total" id="total" style="font-size:18px;font-weight:600;">Rs.<%= f.price %></p>
        <%= link_to "Delete",cart_path(f),method: :delete,class: "btn btn-sm btn-danger px-4 font-weight-bold text-white",style: "position:absolute;right:0;bottom:0;font-size:14px;border-radius:0;" %>

<button type="button" style = "position:absolute;left:0;bottom:0;font-size:14px;border-radius:0;" class="btn btn-sm btn-success px-4 font-weight-bold" data-toggle="modal" data-target="#exampleModal">
  Order
</button>


<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header" style="background:#ff5d0b;">
        <h5 class="modal-title text-white text-center  font-weight-bold" id="exampleModalLabel" style="margin-left: 145px;">Mode of Payment</h5>
        <button type="button" class="close font-weight-bold text-dark" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
      <div class="d-flex justify-content-between mt-3 mb-2">
      <button class= "enablecash  btn btn-sm btn-dark text-white py-2 px-3" style="border-radius:0;">Cash On Delivery</button>
      <button class= "enableonline btn btn-sm btn-dark text-white py-2 px-3", style= "border-radius:0;">Online Payment</button>
      </div>
      <div class="cash">
      <%=form_for :order, :url => {:controller => 'orders',:action => "create"}, :method => "post" do |order| %>
        <div class="field d-flex justify-content-center">
        <%= order.text_area :address,placeholder: "Address",class: "form-control loginbox",:required => true %>
        <%= order.hidden_field :f, :value => f["id"] %>
        </div>
      <div class="d-flex justify-content-center my-3">
      <%= order.submit "Order" ,class: "font-weight-bold btn btn-dark btn-sm px-3  py-2",style: "border-radius:0;" %>
        </div>
    <% end %>
    </div>
<div class="online">
    <%=form_for :order, :url => {:controller => 'paytm',:action => "start_payment"}, :method => "post" do |order| %>
      <div class="field d-flex justify-content-center">
      <%= order.text_area :address,placeholder: "Address",class: "form-control loginbox",:required => true %>
      <%= order.hidden_field :f, :value => f["id"] %>
      </div>
      <div class="d-flex justify-content-center my-3">
      <%= order.submit "Order" ,class: "font-weight-bold btn btn-dark btn-sm px-3  py-2",style: "border-radius:0;" %>
        </div>
  <% end %>
      </div>
      </div>
    </div>
  </div>
</div>
        </div>

 </div>
<% end %>
</div>
<% end %>
</div>

app/views/orders/index.html.erb
<div class="container">
<% if @order_item.size<1 %>
<div class="back mt-5">
<div class="cartempty">
<p class="font-weight-bold text-secondary text-center font-italic" style="font-size:20px;">Your Orders list is empty</p>
<p class="text-center text-muted font-italic">You can go to home page to view more restaurants</p>
    <%= link_to "Add items",landingpage_index_path,class: "d-flex justify-content-center font-weight-bold btn px-4 text-white sa" %>
   </div>
    </div>
<% else %>
<p class="text-left my-5 pb-4 font-italic" style="font-size:22px;font-weight:600;border-bottom:2px solid gray;">YOUR ORDERS</p>
<div class="row">
<div class="col-lg-12">
<% @order_item.each do|f| %>
    <div class="row cart py-3 pr-3 mx-2 mb-4" style="background:alicewhite;">
    <div class="col-4">
    <%= image_tag f["img"],class: "card-img" %>
    </div>
    <div class="col-8">
    <p class="text-muted text-left m-0 p-0 font-weight-bold"><%= f.hotel.upcase %></p>
    <div class="d-flex justify-content-between mt-3">  
       <div class="d-flex">
       <% if f["foodtype"]==="veg" %>
       <img style="margin-top:3px;" src="https://oslocks.files.wordpress.com/2014/11/vegetarian-symbol.png" width="20"  height="20"/>
       <% else %>
       <img style="margin-top:5px;" src="https://infoseekershub.com/wp-content/uploads/2019/08/non-veg.jpg" width="15"  height="15"/>
       <% end %>
        <h5 class="ml-2"><%= f["name"].capitalize %></h5>
        </div>
        </div>
        <p class="font-weight-normal text-muted total" id="total" style="font-size:18px;font-weight:600;">Rs.<%= f.price %></p>
        <%= link_to "Delete",order_path(f),method: :delete,class: "btn btn-sm btn-danger px-4 font-weight-bold text-white",style: "position:absolute;right:0;bottom:0;font-size:14px;border-radius:0;" %>
        <%= link_to "View",order_path(f),class: "btn btn-sm btn-success px-4 font-weight-bold",style: "position:absolute;left:0;bottom:0;font-size:14px;border-radius:0;" %>
    </div>
    </div>
        <% end %>
    
    </div>
  </div>
<% end %>

</div>

app/views/orders/new.html.erb
<h1>New</h1>

app/views/orders/show.html.erb
<div class="container">

<div class="my-4">
<h3 class="text-center font-weight-bold"> <%= @ordered_item.name.upcase %> </h3>
</div>
<div class="text-left">

<div class="d-flex">
<h5 class="font-weight-bold mr-2">HOTEL:</h5>
<p class="font-weight-normal"><%= @ordered_item.hotel %></p>
</div>
<div class="d-flex">
<h5 class="font-weight-bold mr-2">PRICE:</h5>
<p class="font-weight-normal"><%= @ordered_item.price %></p>
</div>
<div class="d-flex">
<h5 class="font-weight-bold mr-2">ADDRESS:</h5>
<p class="font-weight-normal"><%= @ordered_item.address %></p>
</div>

</div>
<script
src="https://api.tiles.mapbox.com/mapbox.js/plugins/turf/v2.0.0/turf.min.js"
charset="utf-8"
></script>
<div class="overlay d-none">
<button id="replay">Replay</button>
</div>
<h4 class="font-weight-bold text-left mt-3">
YOUR ORDER TRACKING : 
</h4>
<div class="font-weight-normal d-flex my-3"><h6 class="font-weight-bold font-italic">Total Distance : <span id="distance"></span> </h6></div>
<div class="mt-3  mb-5 d-flex justify-content-center">
<div id='map'  style='width: 800px; height: 500px;'></div>
</div>
<script>
mapboxgl.accessToken = 'pk.eyJ1IjoibWFoYXBlcml5YXZhcjEwMCIsImEiOiJjazVkcmdjZm0xcnZvM2RyZjQxcjBqcmFrIn0.9iPjpKepyPv5wEdNmfL2Ug';
var map = new mapboxgl.Map({
container: 'map',
style: 'mapbox://styles/mapbox/streets-v11',
center: [77.0188,11.0318],
zoom:12
});
var new_york = new mapboxgl.LngLat(77.0188,11.0318);
var los_angeles = new mapboxgl.LngLat(<%= @result.longitude %>,<%= @result.latitude %>);
sample = new_york.distanceTo(los_angeles);
document.getElementById("distance").innerHTML = Math.round(sample/1000) + "Km"
var marker = new mapboxgl.Marker()
.setLngLat([77.0188,11.0318])
.addTo(map);

var marker = new mapboxgl.Marker()
.setLngLat([<%= @result.longitude %>,<%= @result.latitude %>])
.addTo(map);




var origin = [77.0188,11.0318];
var destination = [<%= @result.longitude %>,<%= @result.latitude %>];
var route = {
'type': 'FeatureCollection',
'features': [
{
'type': 'Feature',
'geometry': {
'type': 'LineString',
'coordinates': [origin, destination]
}
}
]
};
var point = {
'type': 'FeatureCollection',
'features': [
{
'type': 'Feature',
'properties': {},
'geometry': {
'type': 'Point',
'coordinates': origin
}
}
]
};
 
var lineDistance = turf.lineDistance(route.features[0], 'kilometers'); 
var arc = [];
var steps = 30000;
for (var i = 0; i < lineDistance; i += lineDistance / steps) {
var segment = turf.along(route.features[0], i, 'kilometers');
arc.push(segment.geometry.coordinates);
}
route.features[0].geometry.coordinates = arc;
var counter = 0;
map.on('load', function() {
map.addSource('route', {
'type': 'geojson',
'data': route
});
 
map.addSource('point', {
'type': 'geojson',
'data': point
});
 
map.addLayer({
'id': 'route',
'source': 'route',
'type': 'line',
'paint': {
'line-width': 6,
'line-color': '#888'
}
});
 
map.addLayer({
'id': 'point',
'source': 'point',
'type': 'symbol',
'layout': {
'icon-image': 'airport-15',
'icon-rotate': ['get','bearing'],
'icon-size': 1.5,
'icon-rotation-alignment': 'map',
'icon-allow-overlap': true,
'icon-ignore-placement': true
}
});
 
function animate() {
point.features[0].geometry.coordinates =
route.features[0].geometry.coordinates[counter];
point.features[0].properties.bearing = turf.bearing(
turf.point(
route.features[0].geometry.coordinates[
counter >= steps ? counter - 1 : counter
]
),
turf.point(
route.features[0].geometry.coordinates[
counter >= steps ? counter : counter + 1
]
)
);
map.getSource('point').setData(point);
if (counter < steps) {
requestAnimationFrame(animate);
}
counter = counter + 1;
}
document.getElementById('replay').addEventListener('click', function() {
point.features[0].geometry.coordinates = origin;
map.getSource('point').setData(point);
counter = 0;
animate(counter);
});
animate(counter);
});

</script>

</div>