config/routes.rb
Rails.application.routes.draw do
  match 'check/:id' => 'homepage#check' , via: [:post], :as => :check
  match '/paytm_payment' => 'paytm#start_payment', via: [:post], :as => :paytm_payment
  match '/confirm_payment' => 'paytm#verify_payment', via: [:post]
  devise_for :users
  get '/landingpage/map/:id', to: 'landingpage#map', :as => :map
  resources:admin
 resources :homepage
 resources :landingpage
 resources :cart
 resources :orders
 authenticated :user do
  root 'landingpage#index', as: "authenticated_root"
 end
  root 'homepage#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord
    belongs_to :user
end

app/models/item.rb
class Item < ApplicationRecord
    belongs_to :user
end

app/models/order.rb
class Order < ApplicationRecord
    belongs_to :user
end

app/models/otp.rb
class Otp < ApplicationRecord
end

app/models/search.rb
class Search < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :carts
  has_many :items
  has_many :orders
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  def index
    @items = Item.where(user_id:current_user)
  end

  def new
  end

  def create
    @item = current_user.items.build(item_params)
    if @item.save
      redirect_to admin_index_path
    else
      render "new"
    end
  end

  def destroy
    @f = Item.find(params[:id])
    @f.destroy
    redirect_to admin_index_path
  end

   private
   def item_params
    params.require(:item).permit(:hotel, :name, :describe, :foodtype, :price, :img)
  end
end

app/controllers/cart_controller.rb
class CartController < ApplicationController
  def index
    @cartitem = Cart.where(user_id:current_user)
  end
 def destroy
  @f = Cart.find(params[:id])
  @f.destroy
  redirect_to cart_index_path
 end
end

app/controllers/homepage_controller.rb
class HomepageController < ApplicationController
  require 'openssl'
  OpenSSL::SSL::VERIFY_PEER = OpenSSL::SSL::VERIFY_NONE 

  def index
  end

  def new
  end

  def create
    @sample = mobile_params
    @generate = rand(10 ** 4)
    sendotp = @generate
    @genotp  =Otp.new(otpcode:@generate)
    require 'rubygems' 
    require 'twilio-ruby' 
    account_sid = 'ACaee7fdb632a978373799bd29384bc82f' 
    auth_token = '8c27aa0c2ebe5fcbfe4f6f360b4067bf' 
    @client = Twilio::REST::Client.new(account_sid, auth_token) 
    message = @client.messages.create( 
                                 body: sendotp, 
                                 from: '+12055397687',
                                 to: '+919677861286')
    if @genotp.save
      redirect_to homepage_path(@genotp)
    else
      render "new"
    end
  end

  def show
@otpcode = Otp.find(params[:id])
@id = params[:id]
  end

  def check
    @original = Otp.find(params[:id])
    @sample = get_some
    @original1 = @original.otpcode
    fromform = @sample["otpcode"].to_i
    fromdb = @original1
    if fromform == fromdb
     redirect_to new_user_session_path
    else
      redirect_to homepage_path(@original)
    end
  end

  private
  def get_some
    params.require(:otp).permit(:otpcode)
  end
  def mobile_params
   params.require(:otp).permit(:mobile)
 end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController

    def index
        @order_item = Order.where(user_id:current_user)
    end

    def new
    end

    def show
      @ordered_item = Order.find(params[:id])
      require 'geocoder'
      Geocoder.configure(lookup: :opencagedata, api_key: "887ad43e20e04081a44d6775ed0b7d63")
      @results = Geocoder.search(@ordered_item["address"])
      @result = @results.first
      puts "#{@result.latitude}, #{@result.longitude}" 
    end

    def create
        @s = mobile_params
        @address1 = @s["address"]
        @id1 = @s["f"].to_i
        @data = Cart.find(@id1)
        @item = current_user.orders.build(name:@data.name,hotel:@data.hotel,foodtype:@data.foodtype,img:@data.img,describe:@data.describe,price:@data.price,address:@address1)
        if @item.save
            @data.destroy
        redirect_to order_path(@item)
        end
    end

    def destroy
        @f = Order.find(params[:id])
        @f.destroy
        redirect_to orders_path
       end

    private
    def mobile_params
        params.require(:order).permit(:address,:f)
      end

end

app/controllers/paytm_controller.rb
class PaytmController < ApplicationController
    include PaytmHelper
    skip_before_action :verify_authenticity_token
    def start_payment
      @s = mobile_params
      @address1 = @s["address"]
      @id1 = @s["f"].to_i
      @data = Cart.find(@id1)
      @item = current_user.orders.build(name:@data.name,hotel:@data.hotel,foodtype:@data.foodtype,img:@data.img,describe:@data.describe,price:@data.price,address:@address1)
        if @item.save
            @data.destroy
        end
      start_payment = Paytm::StartPaymentService.new(params, request)
      start_payment.call
      @checksum = start_payment.checksum
      @paytmParam = start_payment.paytmParam
    end
  
    def verify_payment
      paytm_verify = Paytm::VerifyPaymentService.new(params, @cart)
      paytm_verify.call
      @paytmparams = paytm_verify.paytmparams
      @is_valid_checksum = paytm_verify.is_valid_checksum
      @some = Order.last()
      if @is_valid_checksum == true
        if @paytmparams["STATUS"] == "TXN_SUCCESS"
          redirect_to order_path(@some)
        else
          respond_to do |format|
            format.html
          end
        end
      end
    end

    private

    def mobile_params
      params.require(:order).permit(:address,:f)
    end

end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cart_helper.rb
module CartHelper
end

app/helpers/homepage_helper.rb
module HomepageHelper
end

app/helpers/landingpage_helper.rb
module LandingpageHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/otp_helper.rb
module OtpHelper
end

app/helpers/paytm_helper.rb
module PaytmHelper
    require 'paytm/encryption_new_pg.rb'
    include EncryptionNewPG
    def generate_checksum
      new_pg_checksum(@paytmParam,"%SoAmYtc!%E4s6DN").gsub("\n",'')
    end
  
    def verify_checksum
      new_pg_verify_checksum(@paytmparams, @checksum_hash, "%SoAmYtc!%E4s6DN")
    end
end

app/views/admin/index.html.erb
<div class="container justify-content-around mt-4">
<h4 class="mb-2 pb-4" style="font-size: 28px;font-weight: 600;border-bottom:2px solid gray;">Your Items</h4>
</div>
<div class="container mb-5 d-flex justify-content-start">
<%= link_to "Add New Item", new_admin_path,class: "btn font-weight-bold text-white btn-sm px-3", style: "background:#ff5d0b;border-radius:0" %>
</div>
<div class="container">
<div class="row">
<% @items.each  do |f| %>
    <div class=" col-lg-4 mb-5">
    <div class="card" style="width: 18rem;border:0;">
    <%= image_tag f["img"],class: "card-img-top img-fluid" %>
    <div class="card-body">
    <p class="text-muted text-left m-0 p-0 font-weight-bold"><%= f["hotel"].upcase %></p>  
        <div class="card-title d-flex">
       <% if f["foodtype"]==="veg" %>
       <img style="margin-top:3px;" src="https://oslocks.files.wordpress.com/2014/11/vegetarian-symbol.png" width="20"  height="20"/>
       <% else %>
       <img style="margin-top:5px;" src="https://infoseekershub.com/wp-content/uploads/2019/08/non-veg.jpg" width="15"  height="15"/>
       <% end %>

        <h5 class="ml-2"><%= f["name"].capitalize %></h5>
        </div>
        <p class="card-subtitle mb-2 text-muted"><%= f["describe"].capitalize %></p>
        <div class="d-flex justify-content-between">
        <div><p class="text-muted" style="font-weight:600;">Rs.<%= f["price"] %></p></div>
        <div><%= link_to "Delete",admin_path(f),method: :delete,class: "btn btn-sm btn-danger px-4 font-weight-bold text-white",style: "border-radius:0;font-size:14px;" %></div>
        </div>
      </div>
    </div>
    </div>
<% end %>

app/views/admin/new.html.erb
<div style=" position:absolute;
left: 50%;
width:30em;
height:18em;
margin-top:20px;
margin-left: -16em;">
<h4 class="text-center my-2">ADD NEW ITEM</h4>
<%= form_for :item, :url => {:action => "create"}, :method => "post" do |f| %>
    <div class="field d-flex justify-content-center">
      <%= f.text_field :hotel,placeholder: "Hotel Name",class: "form-control loginbox" %>
    </div>
    <div class="field d-flex justify-content-center">
    <%= f.text_field :name,placeholder: "Dish Name",class: "form-control loginbox" %>
  </div>
  <div class="field d-flex justify-content-center">
      <%= f.text_field :foodtype,placeholder: "veg or non-veg",class: "form-control loginbox" %>
    </div>
    <div class="field d-flex justify-content-center">
      <%= f.text_field :describe,placeholder: "Description",class: "form-control loginbox" %>
    </div>
    <div class="field d-flex justify-content-center">
      <%= f.text_field :img,placeholder: "Image Url",class: "form-control loginbox" %>
    </div>
    <div class="field d-flex justify-content-center">
      <%= f.text_field :price,placeholder: "Price in Rs.",class: "form-control loginbox" %>
    </div>
    <div class="actions d-flex justify-content-center">
      <%= f.submit "ADD",class: "my-4 btn btn-block text-white font-weight-bold",style: "background-color:#ff5d0b;border-radius:0;" %>
    </div>
  <% end %>
  </div>
  

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Swiggy</title>
    <%= csrf_meta_tags %>
    

<%= javascript_include_tag 'https://api.mapbox.com/mapbox-gl-js/v1.11.1/mapbox-gl.js' %>
<%= stylesheet_link_tag 'https://api.mapbox.com/mapbox-gl-js/v1.11.1/mapbox-gl.css' %>
<%= javascript_include_tag  "https://api.tiles.mapbox.com/mapbox.js/plugins/turf/v2.0.0/turf.min.js" %>
    <%= stylesheet_link_tag   'https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css' %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag 'https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css' %>
    <%= javascript_include_tag  'https://code.jquery.com/jquery-3.2.1.slim.min.js'  %>
    <%= javascript_include_tag  'https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js' %>
    <%= javascript_include_tag 'https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js' %>

 
    </head>

  <body>
  <%if !user_signed_in? %>
  <li class="d-none font-weight-bold text-danger" >Navbar</li>

<% else %>
<nav class="navbar navbar-expand navbar-white bg-white">
  <a class="navbar-brand" href="http://localhost:3000/landingpage"><img src="https://i.pinimg.com/originals/69/df/f3/69dff3d81877bb46865f656de053e96e.png" width="160" height="40" /></a>

  <div>
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <a class="nav-link text-dark px-4 py-3" data-toggle="modal" data-target="#exampleModal" href="#"><i class="fa fa-search px-3" aria-hidden="true"></i>Search</a>
      </li>
  
      <div style="border-radius:0;" class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
          <div class="modal-content">
            <div class="modal-header" style="background:#ff5d0b;">
              <h5 class="modal-title text-white text-center  font-weight-bold" id="exampleModalLabel" style="margin-left: 145px;">SEARCH ITEMS</h5>
              <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
            <div class="modal-body">
            <%=form_for :order, :url => {:controller => 'landingpage',:action => "create"},:method => "post"  do |order| %>
              <div class="field d-flex justify-content-center">
              <%= order.text_field :search,placeholder: "Search Items by name,hotel",class: "form-control loginbox",:required => true %>
              </div>
            <div class="d-flex justify-content-center my-3">
            <%= order.submit "Search" ,class: "font-weight-bold btn btn-dark btn-sm px-3  py-2",style: "border-radius:0;" %>
              </div>
          <% end %>
            </div>
          
          </div>
        </div>
      </div>

      <li class="nav-item">
        <a class="nav-link text-dark px-4 py-3" href="#"><i class="fa fa-cogs px-3" aria-hidden="true"></i>Offers</a>
      </li>
      <li class="nav-item">
      <a class="nav-link text-dark px-4 py-3" href="http://localhost:3000/orders"><i class="fa fa-info px-3" aria-hidden="true"></i>Orders</a>
    </li>
    <% if user_signed_in? %>
    <li class="nav-item">
    <a class="nav-link text-dark px-4 py-3" data-method="delete" href="http://localhost:3000/users/sign_out"><i class="fa fa-sign-out px-3" aria-hidden="true"></i>Logout</a>
  </li>
    <% else %>
    <li class="nav-item">
    <a class="nav-link text-dark px-4 py-3" href="http://localhost:3000/users/sign_in"><i class="fa fa-user-plus px-3" aria-hidden="true"></i>Signin</a>
  </li>
  <% end %>
  <li class="nav-item">
  <a class="nav-link text-dark px-4 py-3" href="http://localhost:3000/cart"><i class="fa fa-shopping-cart px-3" aria-hidden="true"></i>Cart</a>
</li>
    </ul>
  </div>
</nav>
<% end %>

    <%= yield %>
    <% if alert %>
  <p class="alert  text-center text-white bg-danger font-weight-bold"><%= alert %></p>
  <% end %>
  </body>
</html>